Add SASL authentication support
fluffle/goirc pull request #117
Opened 2022-10-30 10:13 UTC by supertassu

This hacks together support for IRCv3.1 SASL. Currently only SASL PLAIN
is supported, but it's implemented in a way that adding support for
other types should not require too many changes to the current code.

2022-11-14 16:09 UTC, fluffle reviewed
Hi! Thank you for sending this PR, and for being patient -- I don't have a huge amount of time to dedicate to this project any more. 

I would rather pull in a dependency on an external SASL library for Go than re-implement things here. Unfortunately it seems like there isn't one "good" one. I can see three possibilities:

*  https://github.com/beltran/gosasl
* https://github.com/emersion/go-sasl
* https://codeberg.org/mellium/sasl

They appear to have a relatively distinct set of features and supported authentication options. In terms of support, the last appears to be receiving the most commits recently, and is tied to a project (mellium) that uses it. I don't know which auth mechanisms are most used with IRC, so I'm not sure which project fits best from that perspective.

Which one of these libraries would you choose as the SASL authentication provider?

> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/117#-:-NGqrPhs74r81fac2ciW:b-eryqzn)* status: 0 of 5 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-14 17:11 UTC, supertassu commented
Hi @fluffle! Using an external library is a good idea I wish I'd thought about myself before implementing things myself. I've updated the PR to use `emersion/go-sasl`, mostly because the author is active in the IRC development scene.

2022-11-16 09:19 UTC, fluffle requested changes
Thanks! The changes mostly LGTM, but there's some improvements necessary w.r.t. checking errors.

> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/117#-:-NGzis3yB_OkT3Y4y4RK:bisiz5m)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @supertassu)

___
*[`client/handlers.go` line 102 at r2](https://reviewable.io/reviews/fluffle/goirc/117#-NGziQKD-YovWwmXGlJo:-NGziQKD-YovWwmXGlJp:b-v4fkkc) ([raw file](https://github.com/fluffle/goirc/blob/c3913a89efcd3bfd613a102da2ac129ee20b0854/client/handlers.go#L102)):*
> ```Go
> 
> 			mech, ir, err := conn.cfg.Sasl.Start()
> 			conn.saslRemainingData = ir
> ```

Please check the error first, and if there is one continue the loop without altering any client state.
___
*[`client/handlers.go` line 231 at r2](https://reviewable.io/reviews/fluffle/goirc/117#-NGzh6KmAmZZDgET2Mh3:-NGzh6KmAmZZDgET2Mh4:bt1tbpv) ([raw file](https://github.com/fluffle/goirc/blob/c3913a89efcd3bfd613a102da2ac129ee20b0854/client/handlers.go#L231)):*
> ```Go
> 	challenge, err := base64.StdEncoding.DecodeString(line.Args[0])
> 	if err != nil {
> 		// TODO: better error handling here and below
> ```

At this point if we can't decode what the server's sending back it's likely sending back garbage, but I suppose we might get another AUTHENTICATE line?

Logging an error and returning here (and below) is probably Good Enough.



_Code quote:_
```Go
// TODO: better error handling here and below
```
___
*[`client/handlers.go` line 232 at r2](https://reviewable.io/reviews/fluffle/goirc/117#-NGzheMS5H8T0Y-xrlHR:-NGzheMS5H8T0Y-xrlHS:bb7exdr) ([raw file](https://github.com/fluffle/goirc/blob/c3913a89efcd3bfd613a102da2ac129ee20b0854/client/handlers.go#L232)):*
> ```Go
> 	if err != nil {
> 		// TODO: better error handling here and below
> 		logging.Error("Failed to decode SASL challenge", err)
> ```

return after this statement, you can't continue with no decoded challenge.
___
*[`client/handlers.go` line 237 at r2](https://reviewable.io/reviews/fluffle/goirc/117#-NGzhhBPCXSHgLfnq4st:-NGzhhBPCXSHgLfnq4su:bh2goi3) ([raw file](https://github.com/fluffle/goirc/blob/c3913a89efcd3bfd613a102da2ac129ee20b0854/client/handlers.go#L237)):*
> ```Go
> 	response, err := conn.cfg.Sasl.Next(challenge)
> 	if err != nil {
> 		logging.Error("Failed to generate response for SASL challenge", err)
> ```

return after this statement, because again if you don't have a valid response to send back you can't continue.
___
*[`client/sasl_test.go` line 25 at r2](https://reviewable.io/reviews/fluffle/goirc/117#-NGzgs-02JifgQxJrZ-a:-NGzgs-02JifgQxJrZ-b:brsivwz) ([raw file](https://github.com/fluffle/goirc/blob/c3913a89efcd3bfd613a102da2ac129ee20b0854/client/sasl_test.go#L25)):*
> ```Go
> 	s.nc.Send("AUTHENTICATE +")
> 	s.nc.Expect("AUTHENTICATE AGV4YW1wbGUAcGFzc3dvcmQ=")
> 	s.nc.Send("904 test :SASL authentication successful")
> ```

I'd like to see some tests that cover the various failure cases of SASL negotiation.


<!-- Sent from Reviewable.io -->

2022-11-17 10:47 UTC, supertassu reviewed
> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/117)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @fluffle)

___
*[`client/handlers.go` line 102 at r2](https://reviewable.io/reviews/fluffle/goirc/117#-NGziQKD-YovWwmXGlJo:-NH4B5Ml0DFmBnaMYNLD:b-896fix) ([raw file](https://github.com/fluffle/goirc/blob/c3913a89efcd3bfd613a102da2ac129ee20b0854/client/handlers.go#L102)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

Please check the error first, and if there is one continue the loop without altering any client state.
</blockquote></details>

Done.
___
*[`client/handlers.go` line 231 at r2](https://reviewable.io/reviews/fluffle/goirc/117#-NGzh6KmAmZZDgET2Mh3:-NH4BQjtDmjvf1xHx3K-:b5f2w45) ([raw file](https://github.com/fluffle/goirc/blob/c3913a89efcd3bfd613a102da2ac129ee20b0854/client/handlers.go#L231)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

At this point if we can't decode what the server's sending back it's likely sending back garbage, but I suppose we might get another AUTHENTICATE line?

Logging an error and returning here (and below) is probably Good Enough.
</blockquote></details>

If we can't decode what it's sending and don't send a reply, I suspect the authentication workflow would just get stuck. I too think it's good enough for now, considering PLAIN and EXTERNAL (the two most common SASL mechanism with IRC) don't involve additional challenges after the initial one.
___
*[`client/handlers.go` line 232 at r2](https://reviewable.io/reviews/fluffle/goirc/117#-NGzheMS5H8T0Y-xrlHR:-NH4BA7C8kPpoyNMfqek:b-896fix) ([raw file](https://github.com/fluffle/goirc/blob/c3913a89efcd3bfd613a102da2ac129ee20b0854/client/handlers.go#L232)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

return after this statement, you can't continue with no decoded challenge.
</blockquote></details>

Done.
___
*[`client/handlers.go` line 237 at r2](https://reviewable.io/reviews/fluffle/goirc/117#-NGzhhBPCXSHgLfnq4st:-NH4B9WeBnAzpJKHR4rB:b-896fix) ([raw file](https://github.com/fluffle/goirc/blob/c3913a89efcd3bfd613a102da2ac129ee20b0854/client/handlers.go#L237)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

return after this statement, because again if you don't have a valid response to send back you can't continue.
</blockquote></details>

Done.
___
*[`client/sasl_test.go` line 25 at r2](https://reviewable.io/reviews/fluffle/goirc/117#-NGzgs-02JifgQxJrZ-a:-NH4BB7h6hRjZy5Sb1YR:b-7lchxw) ([raw file](https://github.com/fluffle/goirc/blob/c3913a89efcd3bfd613a102da2ac129ee20b0854/client/sasl_test.go#L25)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

I'd like to see some tests that cover the various failure cases of SASL negotiation.
</blockquote></details>

Added a few more tests.


<!-- Sent from Reviewable.io -->

2022-11-27 19:48 UTC, fluffle approved these changes
Sorry this took a bit. Looking good now apart from one minor thing. I'm pretty sure the logging functions take a format string and params, even though they aren't suffixed "f". Once you've fixed that please can you squash everything to a single commit and force-push that for me to merge?

> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/117#-:-NHucFDHAx7hLAfCHFN8:b-n606lo)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @supertassu)

___
*[`client/handlers.go` line 103 at r3](https://reviewable.io/reviews/fluffle/goirc/117#-NHubfDXA-6QweUb0JbZ:-NHubfDY6YD2ONxyHXJw:b-i8j2do) ([raw file](https://github.com/fluffle/goirc/blob/558c6a405f2d91a7e3598117a39ccc1dc163bbb5/client/handlers.go#L103)):*
> ```Go
> 
> 			if err != nil {
> 				logging.Warn("SASL authentication failed", err)
> ```

This is a format-string rather than a concatenation IIRC so you want to add ": %v".


<!-- Sent from Reviewable.io -->

2022-11-27 20:02 UTC, supertassu reviewed
Sure! Should be fixed now.

> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/117#-:-NHufmmy6-GI-JycpTzt:b-g5769f)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @fluffle)

___
*[`client/handlers.go` line 103 at r3](https://reviewable.io/reviews/fluffle/goirc/117#-NHubfDXA-6QweUb0JbZ:-NHuflFO9VGxs_1U_MMc:b-896fix) ([raw file](https://github.com/fluffle/goirc/blob/558c6a405f2d91a7e3598117a39ccc1dc163bbb5/client/handlers.go#L103)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

This is a format-string rather than a concatenation IIRC so you want to add ": %v".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-28 09:05 UTC, merged

2022-11-28 13:41 UTC, fluffle commented
Done, and thank you for your contribution :-)